#===================================== Application Data =============================#
server:
  port: 9000
spring:
  application:
    name: spring-cloud-gateway
#================================== Eureka Server Registre ==========================#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#======================= Hystrix Configration (Pending) =============================#      
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
#=========================== Ribbon Configuration (Pending) ========================#
#ribbon:
#  ReadTimeout: 60000
#============================ Zuul Configuration (Pending) =========================#
#zuul:
#  sensitiveHeaders: Cookie,Set-Cookie
#  host:
#    connect-timeout-millis: 60000
#============================= Logging Configuration ===============================#
logging:
  level:
    org:
      springframework:
        web: DEBUG
        ws:
          client:
            MessageTracing:
              received: TRACE
              sent: DEBUG
          server:
            MessageTracing:
              received: TRACE
              sent: DEBUG