#================ Datos de la aplicacion =================#
server:
  port: 8081
spring:
  application:
    name: spring-boot-api-department
  main:
    allow-bean-definition-overriding: true
#================ Configuracion de Eureka =================#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#================= Configuracion de Feign =================#
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
#============== Configuracion de Actuator =================#
management:
  endpoints:
    web:
      exposure:
        include: '*'
#=================== Configuracion de Log4 =================#
logging:
  level:
    org:
      springframework:
        web: DEBUG
        ws:
          client:
            MessageTracing:
              received: TRACE
              sent: DEBUG
          server:
            MessageTracing:
              received: TRACE
              sent: DEBUG 
